### ISSUE TITLE
Missing "type": "module" in package.json

### ISSUE THREAD

**Issue by crystalfp** [othree/smartypants.js#19]
Loading this  package (v 0.1.6) indirectly through the `marked-smartypants` v. 1.0.1 one in this environment:
- node 19.8.1
- OS: Windows 11 64bits
gives the following error:
```
(node:45608) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
D:\Projects\VUEIdeaIgniterEnvironment\server\node_modules\smartypants\smartypants.es6.js:752
export { SmartyPants as smartypants };
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1195:20)
    at Module._compile (node:internal/modules/cjs/loader:1239:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Function.Module._load (node:internal/modules/cjs/loader:972:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

The quick and dirty workaround was to add the line `"type": "module"` to the `package.json` file. Or maybe is the `marked-smartypants` that calls this package wrongly. I'll send them a link to this issue too.
Thanks for considering!
mario

**Comment by crystalfp** [comment]
The issue has been solved in https://github.com/markedjs/marked-smartypants/pull/21 and it is not a problem of this packages as I initially supposed.
Sorry for the noise!
mario

**Comment by UziTech** [comment]
Actually it is a problem with this package. for marked-smartypants I got around it by using rollup to bundle smartypants, but this package currently won't work to import into a node module without something like rollup or babel.

The correct solution is either to use `"type": "module"` or change the file exported for node modules to `smartypants.mjs` like

```diff
"exports": {
  ".": {
-   "import": "./smartypants.es6.js",
+   "import": "./smartypants.mjs",
```

**Comment by crystalfp** [comment]
So you means there is a general problem with `smartypants` package? If yes, could you open an issue with this package? I just closed it (https://github.com/markedjs/marked-smartypants/pull/21).

**Comment by othree** [comment]
Yes, maybe I should add `type: module` since most environments support it already.

**Comment by othree** [comment]
I added the `type`. And change the default export file to the `.mjs` file. Please help test the v0.2.0. Thank you.

**Comment by crystalfp** [comment]
With `marked-smartypants` v. 1.0.2 no more problems, even without the dirty workaround on the `smartypants` package.

**Comment by tunetheweb** [comment]
Yes I think we need that. Also need to change it to this in `package.js`:

```
  "exports": {
    ".": {
      "import": "./smartypants.mjs",
      "require": "./smartypants.cjs"
    }
  },
```

Without that, my CommonJS node program can't import this package from v0.2.0 on :-(
