### ISSUE TITLE
Smartypants is not a function

### ISSUE THREAD

**Issue by jackrieger** [othree/smartypants.js#6]
Error when running this: 

```
var smartypants = require('smartypants');

var attr = 1; // Number or string
var sourceText = '"hello!"';

var educated = smartypants(sourceText, attr);
```

```smartypants is not a function```

**Comment by lonekorean** [comment]
I had the same problem. Then realized that I had to do:

```javascript
var educated = smartypants.smartypants(sourceText, attr);
```

Unless I'm missing something, I think the readme should be updated to reflect this.

**Comment by othree** [comment]
This is caused by the TS transpile to ES part.
So if you use the es6 module version.
The default export is correct.
